// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication6.Context;

#nullable disable

namespace WebApplication6.Migrations
{
    [DbContext(typeof(ShopContext.AppDbContext))]
    [Migration("20240602104032_Shop")]
    partial class Shop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication6.Models.Accounts", b =>
                {
                    b.Property<int>("PK_account")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_account"));

                    b.Property<int>("FK_role")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("PK_account");

                    b.HasIndex("FK_role");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WebApplication6.Models.Categories", b =>
                {
                    b.Property<int>("PK_category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_category"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PK_category");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WebApplication6.Models.Products", b =>
                {
                    b.Property<int>("PK_product")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_product"));

                    b.Property<decimal>("depth")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("width")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("PK_product");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebApplication6.Models.Products_Categories", b =>
                {
                    b.Property<int>("FK_product")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("FK_category")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("FK_product", "FK_category");

                    b.HasIndex("FK_category");

                    b.ToTable("ProductsCategories");
                });

            modelBuilder.Entity("WebApplication6.Models.Roles", b =>
                {
                    b.Property<int>("PK_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PK_role"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PK_role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WebApplication6.Models.Shopping_Carts", b =>
                {
                    b.Property<int>("FK_account")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("FK_product")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.HasKey("FK_account", "FK_product");

                    b.HasIndex("FK_product");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("WebApplication6.Models.Accounts", b =>
                {
                    b.HasOne("WebApplication6.Models.Roles", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("FK_role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApplication6.Models.Products_Categories", b =>
                {
                    b.HasOne("WebApplication6.Models.Categories", "Category")
                        .WithMany("ProductsCategories")
                        .HasForeignKey("FK_category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication6.Models.Products", "Product")
                        .WithMany("ProductsCategories")
                        .HasForeignKey("FK_product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApplication6.Models.Shopping_Carts", b =>
                {
                    b.HasOne("WebApplication6.Models.Accounts", "Account")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("FK_account")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication6.Models.Products", "Product")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("FK_product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApplication6.Models.Accounts", b =>
                {
                    b.Navigation("ShoppingCarts");
                });

            modelBuilder.Entity("WebApplication6.Models.Categories", b =>
                {
                    b.Navigation("ProductsCategories");
                });

            modelBuilder.Entity("WebApplication6.Models.Products", b =>
                {
                    b.Navigation("ProductsCategories");

                    b.Navigation("ShoppingCarts");
                });

            modelBuilder.Entity("WebApplication6.Models.Roles", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
